Vagrant.configure("2") do |config|
    (1..2).each do |i|
      config.vm.define "web-servers#{i}" do |machine|
        machine.vm.box = "ubuntu/focal64"
        machine.vm.hostname = "web-server#{i}"
        machine.vm.network "private_network", ip: "192.168.56.#{10 + i}"
  
        machine.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = 1
        end

        machine.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbook.yml"
          ansible.limit = "web-servers#{i}"
        end
  
      end
    end
  end
  